### ISSUE TITLE
Need some clarification 

### ISSUE THREAD

**Issue by CheeYongLee2001** [MeiqiGuo/ICCV2021-AtypicalityDetection#1]
Hello, I am a university student who would like to run your code, you did mention that we need to modify config but I am not sure what are those variables mean, especially feat_folder, what the folder should be and what should be included in the folder.

Besides, there is a json file called annotation.json which will be called in the function AdsDatasetWithMask, I can't find the annotation.json file, do I need to prepare myself? If yes, what is the content of the json file should include?

**Comment by MeiqiGuo** [comment]
Hello, thank you for your interest in this work.

For the feat_folder, it is about the step 1 described in the README:
Extract the image features by the Faster R-CNN feature extractor demonstrated in ["Bottom-Up and Top-Down Attention for Image Captioning and Visual Question Answering" (CVPR 2018)](https://arxiv.org/abs/1707.07998). You may refer to these github ([1](https://github.com/peteanderson80/bottom-up-attention), [2](https://github.com/airsplay/lxmert#faster-r-cnn-feature-extraction), [3](https://github.com/violetteshev/bottom-up-features)) for the extraction. Please save them and adapt the structure of folders with our code (datasets/ads.py).

With respect to the file named annotation.json, please send me an email and I will send you the data. You can also prepare this file by yourself. The file is a processed version of atypicality annotation presented in https://people.cs.pitt.edu/~kovashka/ads/#image. The processing steps are introduced in our paper section 4.2.

**Comment by CheeYongLee2001** [comment]
Thanks for your reply, my email is clee0116@student.monash.edu, I would like to have the annotation.json file.

I may ask for other questions related to the code when I face other problem afterwards, really appreciated.

**Comment by MeiqiGuo** [comment]
Sure, sent.

**Comment by MeiqiGuo** [comment]
Sure, sent.
